name: Deploy NestJS App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Clonar el repositorio
        uses: actions/checkout@v4

      - name: 🔄 Instalar sshpass
        run: sudo apt-get install -y sshpass

      - name: 🔄 Copiar archivos al servidor
        run: |
          sshpass -p '9d#N2@g02cmE' scp -P 14932 -r -o StrictHostKeyChecking=no * root@45.236.131.22:/root/nestapp

      - name: 🚀 Instalar dependencias y reiniciar app
        run: |
          sshpass -p '9d#N2@g02cmE' ssh -p 14932 -o StrictHostKeyChecking=no root@45.236.131.22 <<EOF
            cd /root/app
            npm install
            npm run build
            pm2 restart all || pm2 start dist/main.js --name nest-app
          EOF
